VAGRANTFILE_API_VERSION = "2"

password = ARGV[0]

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
################
### DEVSTACK ###
################
  config.vm.define "devstack" do |config|
    config.vm.box = "ubuntu/focal64"

    config.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 8192
      v.cpus = 2
    end

    ### OpenStack IP
    config.vm.network "private_network", ip: "10.0.0.25"

    ### horizon (http://10.0.0.25/horizon)
    config.vm.network "forwarded_port", guest: 80, host: 8080

    ### vnc
    config.vm.network "forwarded_port", guest: 6080, host: 6080

    ### neutron api
    config.vm.network "forwarded_port", guest: 9696, host: 9696

    config.ssh.forward_agent = true

    config.vm.hostname = "devstack.vagrant"

    config.vm.provision "shell", path: "scripts/base.sh", privileged: true
    config.vm.provision "shell", path: "scripts/install-devstack.sh", privileged: false, args: [password, "172.25.0.0/24"]

    ### Required to be able to restart vagrant instance without disruption of OpenStack functionality
    config.vm.provision "shell", path: "scripts/fix-bridge-after-reboot.sh", privileged: true, args: ["172.25.0.1/24"]
  end

end
